apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: trigger-gateway
spec:
  template:
    spec:
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/knative-sample/gateway:master_0f27a4dc-20191213170016
          args:
            - --trigger-service=el-acr-trigger-listener
          ports:
            - name: http1
              containerPort: 8080

