--- 
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  inputs:
    params:
    - name: imageUrl
      description: The image full url
    - name: imageTag
      description: The image tag
    - name: imageDigest
      description: The image digest
    - name: namespace
      description: The knative service namespace
    - name: ksvcname
      description: The knative service name
    - name: imageDigest
      description: The knative service image digest
  steps:
    - name: pre-deploy
      image: registry.cn-hangzhou.aliyuncs.com/knative-sample/alpine:3.10.3
      command:
      - sh
      args:
      - -c
      - |
        echo "pre-deploy: success!!"
      volumeMounts:
      - name: result
        mountPath: /app/result/
    - name: deploy
      image: registry.cn-hangzhou.aliyuncs.com/knative-sample/deployer:master_0f27a4dc-20191213170052
      command:
      - sh
      args:
      - -c
      - |
        /deployer --image=$(inputs.params.imageUrl):$(inputs.params.imageTag) --ksvcname=$(inputs.params.ksvcname) --namespace=$(inputs.params.namespace)
        if [ $? -eq 0 ]; then
            echo "SUCCESS" > /app/result/deploy
        else
            echo "FAILED" > /app/result/deploy
        fi
      volumeMounts:
      - name: result
        mountPath: /app/result/
    - name: post-deploy
      image: registry.cn-hangzhou.aliyuncs.com/knative-sample/alpine:3.10.3
      command:
      - sh
      args:
      - -c
      - |
        if grep -Fxq "SUCCESS" /app/result/deploy 2>/dev/null
        then
            echo "post-deploy: --image=$(inputs.params.imageUrl):$(inputs.params.imageTag) --ksvcname=$(inputs.params.ksvcname) --namespace=$(inputs.params.namespace) deploy SUCCESS!!"
        else
            echo "post-deploy: --image=$(inputs.params.imageUrl):$(inputs.params.imageTag) --ksvcname=$(inputs.params.ksvcname) --namespace=$(inputs.params.namespace) deploy FAILED!!"
        fi
      volumeMounts:
      - name: result
        mountPath: /app/result/

  volumes:
  - name: result
    emptyDir: {}

--- 
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: acr-trigger-pipeline
spec:
  params:
  - name: imageUrl
    description: The image full url
  - name: imageTag
    description: The image tag
  - name: imageDigest
    description: The image digest
  - name: namespace
    description: The knative service namespace
  - name: ksvcname
    description: The knative service name
  tasks:
  - name: deploy
    taskRef:
      name: deploy
    params:
    - name: imageUrl
      value: "$(params.imageUrl)"
    - name: imageTag
      value: "$(params.imageTag)"
    - name: imageDigest
      value: "$(params.imageDigest)"
    - name: ksvcname
      value: "$(params.ksvcname)"
    - name: namespace
      value: "$(params.namespace)"

