apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: acr-triggertemplate
spec:
  params:
  - name: imageUrl
    description: The image full url
  - name: imageTag
    description: The image tag
  - name: imageDigest
    description: The image digest
  - name: namespace
    description: The knative service namespace
  - name: ksvcname
    description: The knative service name

  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: acr-trigger-pipeline-run-$(uid)
        namespace: cicd-system
      spec:
        pipelineRef:
          name: acr-trigger-pipeline
        timeout: 0h30m0s
        serviceAccount: tekton-trigger

        params:
        - name: imageUrl
          value: "$(params.imageUrl)"
        - name: imageTag
          value: "$(params.imageTag)"
        - name: imageDigest
          value: "$(params.imageDigest)"
        - name: ksvcname
          value: "$(params.ksvcname)"
        - name: namespace
          value: "$(params.namespace)"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: acr-trigger-pipelinebinding
spec:
  params:
  - name: imageUrl
    value: "registry.$(body.repository.region).aliyuncs.com/$(body.repository.namespace)/$(body.repository.name)"
  - name: imageTag
    value: "$(body.push_data.tag)"
  - name: imageDigest
    value: "$(body.push_data.digest)"
  - name: namespace
    value: "$(header.Namespace)"
  - name: ksvcname 
    value: "$(header.Ksvcname)"

---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: acr-trigger-listener
spec:
  serviceAccountName: tekton-trigger
  triggers:
    - binding:
        name: acr-trigger-pipelinebinding
      template:
        name: acr-triggertemplate

